version: '3.8'
services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    image: proj3a_image
    container_name: proj3a
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"